# Generated by Django 4.2.4 on 2023-10-07 23:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0002_alter_expense_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='time_stamp',
            field=models.CharField(blank=True, choices=[('MINUT', 'Minut'), ('GODZIN', 'Godzin'), ('TYGODNI', 'Tygodni'), ('MIESIĘCY', 'Miesięcy'), ('LAT', 'Lat')], default='MIESIĘCY', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
