# Generated by Django 4.2.4 on 2023-10-13 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0004_guarantee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guarantee',
            name='amount',
        ),
    ]
