# Generated by Django 4.2.4 on 2023-10-13 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0007_alter_guarantee_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='receipt_info',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
