# Generated by Django 4.2.4 on 2023-10-22 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0008_receipt_receipt_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, max_length=400, null=True)),
            ],
            options={
                'verbose_name_plural': 'list products',
            },
        ),
        migrations.AddField(
            model_name='receipt',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, to='receipts.listproduct'),
        ),
    ]
