# Generated by Django 4.2.4 on 2023-11-18 17:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0017_alter_guarantee_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='receipt_text_read_by_OCR',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='guarantee',
            name='end_date',
            field=models.DateField(default=datetime.date(2023, 11, 18)),
        ),
    ]
