# Generated by Django 4.2.4 on 2023-11-18 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0018_receipt_receipt_text_read_by_ocr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='products',
            field=models.ManyToManyField(to='receipts.listproduct'),
        ),
    ]
