# Generated by Django 4.2.4 on 2023-11-18 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0021_alter_receipt_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='products',
            field=models.ManyToManyField(blank=True, to='receipts.listproduct'),
        ),
    ]
