# Generated by Django 4.2.4 on 2023-11-19 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0015_product_description'),
        ('receipts', '0025_unaccent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='products',
            field=models.ManyToManyField(blank=True, to='categories.product'),
        ),
    ]
