# Generated by Django 4.2.4 on 2023-11-19 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0027_receipt_date_of_receipt_bought'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='receipt_pdf',
            field=models.FileField(blank=True, max_length=254, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='receipt_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
