# Generated by Django 4.2.4 on 2023-11-19 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0015_product_description'),
        ('receipts', '0028_receipt_receipt_pdf_alter_receipt_receipt_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='receipt_categories',
            field=models.ManyToManyField(related_name='receipt_categories', to='categories.basecategories'),
        ),
    ]
