# Generated by Django 4.2.4 on 2023-11-19 19:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0015_product_description'),
        ('receipts', '0029_receipt_receipt_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='date_of_receipt_bought',
            field=models.DateField(blank=True, default=datetime.date(2023, 11, 19), null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='receipt_categories',
            field=models.ManyToManyField(blank=True, related_name='receipt_categories', to='categories.basecategories'),
        ),
    ]
