# Generated by Django 4.2.4 on 2023-11-22 01:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promotions_and_discounts', '0010_remove_shop_slug_shop_category_shop_promos_available_and_more'),
        ('receipts', '0032_alter_expense_time_stamp_alter_guarantee_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='is_starred',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='receipt',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='promotions_and_discounts.shop'),
        ),
        migrations.AlterField(
            model_name='guarantee',
            name='end_date',
            field=models.DateField(default=datetime.date(2023, 11, 22)),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='date_of_receipt_bought',
            field=models.DateField(blank=True, default=datetime.date(2023, 11, 22), null=True),
        ),
    ]
