# Generated by Django 4.2.4 on 2023-11-22 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0033_receipt_is_starred_receipt_shop_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
