# Generated by Django 4.2.4 on 2023-11-22 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0034_alter_receipt_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='is_starred',
            field=models.BooleanField(default=False),
        ),
    ]
