# Generated by Django 4.2.4 on 2023-11-23 19:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0035_expense_is_starred'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='receipt_pdf',
        ),
        migrations.AlterField(
            model_name='guarantee',
            name='end_date',
            field=models.DateField(default=datetime.date(2023, 11, 23)),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='date_of_receipt_bought',
            field=models.DateField(blank=True, default=datetime.date(2023, 11, 23), null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='receipt_img',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
