# Generated by Django 4.2.4 on 2023-11-23 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0036_remove_receipt_receipt_pdf_alter_guarantee_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='receipt_name',
            field=models.CharField(default='Nowy paragon', max_length=200),
        ),
    ]
