# Generated by Django 4.2.4 on 2023-11-23 22:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0037_alter_receipt_receipt_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guarantee',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2023, 11, 23, 22, 6, 44, 68498, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='date_of_receipt_bought',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 11, 23, 22, 6, 44, 66498, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
