# Generated by Django 4.2.4 on 2023-12-01 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0043_guarantee_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='time_stamp',
            field=models.CharField(blank=True, choices=[('DNI', 'Dni'), ('MIESIĘCY', 'Miesięcy'), ('LAT', 'Lat')], default='MIESIĘCY', max_length=12, null=True),
        ),
    ]
