# Generated by Django 4.2.4 on 2023-12-01 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0044_alter_expense_time_stamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guarantee',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='receipt',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
