# Generated by Django 4.2.4 on 2024-01-09 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0046_expense_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='ended_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
