# Generated by Django 4.2.4 on 2024-01-09 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0047_expense_ended_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='ended_date',
        ),
    ]
