# Generated by Django 4.2.4 on 2023-10-17 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_mangement', '0002_alter_profileinfo_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileinfo',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profileinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
