# Generated by Django 4.2.4 on 2023-10-17 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_mangement', '0003_profileinfo_date_of_birth_profileinfo_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileinfo',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
