# Generated by Django 4.2.4 on 2023-10-17 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_mangement', '0005_profileinfo_profile_image_background_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileinfo',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
