# Generated by Django 4.2.4 on 2023-11-05 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_mangement', '0008_alter_profileinfo_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileinfo',
            name='messages_by_groups',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profileinfo',
            name='messages_by_users',
            field=models.BooleanField(default=True),
        ),
    ]
