# Generated by Django 4.2.4 on 2023-11-05 01:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profile_mangement', '0009_profileinfo_messages_by_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileinfo',
            name='blocked_users',
            field=models.ManyToManyField(related_name='blocked_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
