# Generated by Django 4.2.4 on 2023-11-05 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_mangement', '0010_profileinfo_blocked_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileinfo',
            name='how_many_expenses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profileinfo',
            name='how_many_guarantees',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profileinfo',
            name='how_many_receipts',
            field=models.IntegerField(default=0),
        ),
    ]
