# Generated by Django 4.2.4 on 2023-11-06 01:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profile_mangement', '0011_profileinfo_how_many_expenses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileinfo',
            name='blocked_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='blocked_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
