# Generated by Django 4.2.4 on 2023-11-06 02:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profile_mangement', '0012_alter_profileinfo_blocked_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileinfo',
            name='blocked_users',
            field=models.ManyToManyField(blank=True, related_name='blocked_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
