# Generated by Django 4.2.4 on 2023-12-01 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_mangement', '0014_alter_profileinfo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileinfo',
            name='how_many_expenses',
        ),
        migrations.RemoveField(
            model_name='profileinfo',
            name='how_many_guarantees',
        ),
        migrations.RemoveField(
            model_name='profileinfo',
            name='how_many_receipts',
        ),
    ]
