# Generated by Django 4.2.4 on 2023-12-28 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_mangement', '0015_remove_profileinfo_how_many_expenses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileinfo',
            name='text',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
