# Generated by Django 4.2.4 on 2023-10-06 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0048_alter_commongroups_password'),
        ('my_messages', '0002_message_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.commongroups'),
        ),
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(default='normal', max_length=200),
        ),
    ]
