# Generated by Django 4.2.4 on 2023-11-04 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_messages', '0004_alter_message_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
