# Generated by Django 4.2.4 on 2023-11-04 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_messages', '0005_alter_message_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='slug',
        ),
    ]
