# Generated by Django 4.2.4 on 2023-11-04 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_messages', '0006_remove_message_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_seen_by_sender',
            field=models.BooleanField(default=True),
        ),
    ]
