# Generated by Django 4.2.4 on 2023-11-06 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_messages', '0008_message_is_seen_by_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='answered',
            field=models.BooleanField(default=False),
        ),
    ]
