# Generated by Django 4.2.4 on 2023-09-25 19:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory_name', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=7)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('slug', models.SlugField(null=True, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='customcategories',
            name='owner',
        ),
        migrations.AddField(
            model_name='basecategories',
            name='owner',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='category_owner', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='BaseSubCategories',
        ),
        migrations.DeleteModel(
            name='CustomCategories',
        ),
        migrations.AddField(
            model_name='subcategories',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.basecategories'),
        ),
        migrations.AddField(
            model_name='subcategories',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategory_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
