# Generated by Django 4.2.4 on 2023-09-25 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_subcategories_remove_customcategories_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basecategories',
            name='icon',
            field=models.CharField(default='', max_length=1),
        ),
        migrations.AddField(
            model_name='basecategories',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
