# Generated by Django 4.2.4 on 2023-09-25 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_basecategories_icon_basecategories_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategories',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
