# Generated by Django 4.2.4 on 2023-09-25 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_subcategories_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecategories',
            name='icon',
            field=models.CharField(blank=True, default='', max_length=1),
        ),
    ]
