# Generated by Django 4.2.4 on 2023-10-02 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_alter_basecategories_icon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basecategories',
            options={'verbose_name_plural': 'Base categories'},
        ),
        migrations.AlterModelOptions(
            name='subcategories',
            options={'verbose_name_plural': 'Subcategories'},
        ),
    ]
