# Generated by Django 4.2.4 on 2023-10-08 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0007_alter_basecategories_icon_alter_basecategories_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecategories',
            name='icon',
            field=models.CharField(blank=True, default='', max_length=1500),
        ),
    ]
