# Generated by Django 4.2.4 on 2023-10-11 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0008_alter_basecategories_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategories',
            name='icon',
            field=models.CharField(blank=True, default='', max_length=1500),
        ),
        migrations.AlterField(
            model_name='basecategories',
            name='color',
            field=models.CharField(default='#233423', max_length=7),
        ),
    ]
