# Generated by Django 4.2.4 on 2023-11-18 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('categories', '0011_remove_subcategories_slug_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecategories',
            name='owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subcategories',
            name='category',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.basecategories'),
        ),
        migrations.AlterField(
            model_name='subcategories',
            name='owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategory_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
