# Generated by Django 4.2.4 on 2023-11-18 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0013_alter_subcategories_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Products'},
        ),
    ]
