# Generated by Django 4.2.4 on 2023-11-19 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0014_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
    ]
