# Generated by Django 4.2.4 on 2023-11-20 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0015_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
    ]
