# Generated by Django 4.2.4 on 2023-11-21 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0016_remove_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basecategories',
            name='slug',
        ),
    ]
