# Generated by Django 4.2.4 on 2023-12-01 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0017_remove_basecategories_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basecategories',
            name='slug',
        ),
    ]
