# Generated by Django 4.2.4 on 2023-12-05 06:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('categories', '0018_remove_basecategories_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecategories',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
