# Generated by Django 4.2.4 on 2023-10-16 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions_and_discounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='link',
            field=models.CharField(default='https://www.lidl.pl/q/query/wyprzedaz', max_length=2000),
            preserve_default=False,
        ),
    ]
