# Generated by Django 4.2.4 on 2023-10-16 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions_and_discounts', '0004_alter_shop_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
