# Generated by Django 4.2.4 on 2023-10-16 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotions_and_discounts', '0006_alter_shop_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='slug',
        ),
    ]
