# Generated by Django 4.2.4 on 2023-10-16 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions_and_discounts', '0007_remove_shop_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='slug',
            field=models.SlugField(default='nie ma', unique=True),
            preserve_default=False,
        ),
    ]
