# Generated by Django 4.2.4 on 2023-11-19 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0014_alter_product_options'),
        ('promotions_and_discounts', '0009_alter_shop_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='slug',
        ),
        migrations.AddField(
            model_name='shop',
            name='category',
            field=models.ManyToManyField(to='categories.basecategories'),
        ),
        migrations.AddField(
            model_name='shop',
            name='promos_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shop',
            name='link',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
