# Generated by Django 4.2.4 on 2023-12-04 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions_and_discounts', '0010_remove_shop_slug_shop_category_shop_promos_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='map_names',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='nip',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
