# Generated by Django 4.2.4 on 2024-01-07 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions_and_discounts', '0011_shop_map_names_shop_nip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='shop_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
