# Generated by Django 4.2.4 on 2023-09-03 18:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0002_rename_group_common_groups'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Common_Groups',
            new_name='CommonGroups',
        ),
    ]
