# Generated by Django 4.2.4 on 2023-09-17 16:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0003_rename_common_groups_commongroups'),
    ]

    operations = [
        migrations.AddField(
            model_name='commongroups',
            name='max_number_of_members',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='commongroups',
            name='members',
            field=models.ManyToManyField(related_name='member', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commongroups',
            name='password',
            field=models.CharField(default='%~|(1\\{QI5(R9y{(|V|Y', max_length=200),
        ),
        migrations.AddField(
            model_name='commongroups',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AlterField(
            model_name='commongroups',
            name='number_of_members',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='commongroups',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
