# Generated by Django 4.2.4 on 2023-09-17 17:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_commongroups_max_number_of_members_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commongroups',
            name='number_of_members',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(50), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='commongroups',
            name='password',
            field=models.CharField(default="y}1K#J'P+9XWz+18b+Bc", max_length=200),
        ),
    ]
