# Generated by Django 4.2.4 on 2023-09-24 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_alter_commongroups_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commongroups',
            name='password',
            field=models.CharField(default='eLLgZd(xZ3PnlRx&?dQ4', max_length=200),
        ),
    ]
