# Generated by Django 4.2.4 on 2023-09-24 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0007_alter_commongroups_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commongroups',
            name='password',
            field=models.CharField(default='8(ki6ZmZ4!lYZIU9kVMs', max_length=200),
        ),
    ]
