# Generated by Django 4.2.4 on 2023-09-24 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0008_alter_commongroups_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commongroups',
            name='password',
            field=models.CharField(default='kB)ID*q%&tQ@79!6mmkb', max_length=200),
        ),
    ]
