# Generated by Django 4.2.4 on 2023-09-24 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0009_alter_commongroups_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commongroups',
            name='password',
            field=models.CharField(default='x0m%8oGl8yOz)XdpIm)g', max_length=200),
        ),
    ]
