# Generated by Django 4.2.4 on 2023-09-25 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0011_alter_commongroups_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commongroups',
            name='password',
            field=models.CharField(default='VIzs10)jD?EG=/lqE>>L', max_length=200),
        ),
    ]
