# Generated by Django 4.2.4 on 2023-09-25 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0013_alter_commongroups_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commongroups',
            name='password',
            field=models.CharField(default='M*l&o6iHd9khCURt6nPO', max_length=200),
        ),
    ]
