# Generated by Django 4.2.4 on 2023-09-25 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0014_alter_commongroups_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commongroups',
            name='password',
            field=models.CharField(default='fd>pFy7>4Y0kskYOhV!$', max_length=200),
        ),
    ]
