# Generated by Django 4.2.4 on 2023-09-25 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0015_alter_commongroups_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commongroups',
            name='password',
            field=models.CharField(default='zB7)1XR8acQ.1lvoa!w>', max_length=200),
        ),
    ]
