# Generated by Django 4.2.4 on 2023-09-25 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0018_alter_commongroups_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commongroups',
            name='password',
            field=models.CharField(default='lI3yMz8qoxq2acbII0%3', max_length=200),
        ),
    ]
