# Generated by Django 4.2.4 on 2023-10-02 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0020_alter_commongroups_group_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commongroups',
            options={'verbose_name_plural': 'Common groups'},
        ),
        migrations.AlterField(
            model_name='commongroups',
            name='password',
            field=models.CharField(default='cp7nZmT3LVO<&GSQ8qw7', max_length=200),
        ),
    ]
