# Generated by Django 4.2.4 on 2023-10-02 20:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0021_alter_commongroups_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commongroups',
            name='max_number_of_members',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MaxValueValidator(50), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='commongroups',
            name='number_of_members',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(50), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='commongroups',
            name='password',
            field=models.CharField(default='mP!ed*.6+4=Fk3-jpa./', max_length=200),
        ),
    ]
