# Generated by Django 4.2.4 on 2023-10-02 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0022_alter_commongroups_max_number_of_members_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commongroups',
            name='password',
            field=models.CharField(default='.rQBIo*P0oZS6gR-Eh95', max_length=200),
        ),
    ]
