# Generated by Django 4.2.4 on 2023-10-04 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0023_alter_commongroups_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commongroups',
            name='password',
            field=models.CharField(default='HzWO?m5+juNVJcc!VaWe', max_length=200),
        ),
    ]
