# Generated by Django 4.2.4 on 2023-10-04 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0028_alter_commongroups_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commongroups',
            name='password',
            field=models.CharField(default='jcfUGJpfv4YdGDs2myZ9', max_length=200),
        ),
    ]
