# Generated by Django 4.2.4 on 2023-10-04 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0029_alter_commongroups_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commongroups',
            name='password',
            field=models.CharField(default='Kzif4jh31F&f7gOiR4?T', max_length=200),
        ),
    ]
