# Generated by Django 4.2.4 on 2023-10-04 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0030_alter_commongroups_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commongroups',
            name='password',
            field=models.CharField(default='smWGQ>w!)F?e+YpYH3OR', max_length=200),
        ),
    ]
