# Generated by Django 4.2.4 on 2023-10-06 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0032_alter_commongroups_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commongroups',
            name='password',
            field=models.CharField(default='<tRGm0F0es@>mXuy>N9L', max_length=200),
        ),
    ]
