# Generated by Django 4.2.4 on 2023-10-06 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0034_alter_commongroups_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commongroups',
            name='password',
            field=models.CharField(default='EPt6uu48j8)!LAfA3l1%', max_length=200),
        ),
    ]
