# Generated by Django 4.2.4 on 2023-10-06 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0036_alter_commongroups_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commongroups',
            name='password',
            field=models.CharField(default='Q*5mo2!CGeWfod!bcnj5', max_length=200),
        ),
    ]
