# Generated by Django 4.2.4 on 2023-10-06 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0037_alter_commongroups_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commongroups',
            name='password',
            field=models.CharField(default='K>NemI+9UuV<9EQ0u0Q?', max_length=200),
        ),
    ]
