# Generated by Django 4.2.4 on 2023-10-06 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0038_alter_commongroups_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commongroups',
            name='password',
            field=models.CharField(default='DC.YyENROLmcqw01okU&', max_length=200),
        ),
    ]
