# Generated by Django 4.2.4 on 2023-10-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0039_alter_commongroups_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commongroups',
            name='password',
            field=models.CharField(default='q4m5N5kSE9)&39gT$S=M', max_length=200),
        ),
    ]
