# Generated by Django 4.2.4 on 2023-10-06 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0041_alter_commongroups_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commongroups',
            name='password',
            field=models.CharField(default='a0fD4+do&p.eJS&O.yqC', max_length=200),
        ),
    ]
