# Generated by Django 4.2.4 on 2023-10-06 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0043_alter_commongroups_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commongroups',
            name='password',
            field=models.CharField(default='l%QDK*a3Iv!.(lC4T3f8', max_length=200),
        ),
    ]
