# Generated by Django 4.2.4 on 2023-10-06 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0044_alter_commongroups_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commongroups',
            name='password',
            field=models.CharField(default='0V<rAOYV-GFa8D/r-V@$', max_length=200),
        ),
    ]
