# Generated by Django 4.2.4 on 2023-10-06 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0046_alter_commongroups_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commongroups',
            name='password',
            field=models.CharField(default='d45(X2mT-VGgHVp77%j&', max_length=200),
        ),
    ]
