# Generated by Django 4.2.4 on 2023-10-06 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0050_alter_commongroups_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commongroups',
            name='password',
            field=models.CharField(default='FiXz$Tvv)m9I6Le4BabH', max_length=200),
        ),
    ]
