# Generated by Django 4.2.4 on 2023-10-07 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0053_alter_commongroups_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commongroups',
            name='password',
            field=models.CharField(default='R6X3Dpm6VE)Sz)Es4U*6', max_length=200),
        ),
    ]
