# Generated by Django 4.2.4 on 2023-10-08 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0054_alter_commongroups_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commongroups',
            name='password',
            field=models.CharField(default='U$LuDH$b?+e/EA<E$?Rx', max_length=200),
        ),
    ]
