# Generated by Django 4.2.4 on 2023-10-08 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0055_alter_commongroups_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commongroups',
            name='password',
            field=models.CharField(default='l>@sokl&!LsOePJ=@jSr', max_length=200),
        ),
    ]
