# Generated by Django 4.2.4 on 2023-10-08 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0056_alter_commongroups_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commongroups',
            name='password',
            field=models.CharField(default='iGi&j?xhPxBS(3m4RPCU', max_length=200),
        ),
    ]
