# Generated by Django 4.2.4 on 2023-10-13 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0059_alter_commongroups_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commongroups',
            name='password',
            field=models.CharField(default='f.7qT/)2faX3pmc%O-$w', max_length=200),
        ),
    ]
