# Generated by Django 4.2.4 on 2023-10-13 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0062_alter_commongroups_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commongroups',
            name='password',
            field=models.CharField(default='Z.z3(v1-?55dzX1x?AK*', max_length=200),
        ),
    ]
