# Generated by Django 4.2.4 on 2023-10-13 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0063_alter_commongroups_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commongroups',
            name='password',
            field=models.CharField(default='vxwEsc/264&gex+vppfD', max_length=200),
        ),
    ]
