# Generated by Django 4.2.4 on 2023-10-14 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0064_alter_commongroups_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commongroups',
            name='password',
            field=models.CharField(default='W.N?HedHF<GVz)nGQi(m', max_length=200),
        ),
    ]
