# Generated by Django 4.2.4 on 2023-10-16 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0065_alter_commongroups_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commongroups',
            name='password',
            field=models.CharField(default='OpWC+OhQOw$3+rHBSKEc', max_length=200),
        ),
    ]
