# Generated by Django 4.2.4 on 2023-10-16 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0066_alter_commongroups_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commongroups',
            name='password',
            field=models.CharField(default='iwkt?PKDEGwm8Qo+9=vZ', max_length=200),
        ),
    ]
