# Generated by Django 4.2.4 on 2023-10-16 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0073_alter_commongroups_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commongroups',
            name='password',
            field=models.CharField(default='UpMN&B>jL1sOc$tEU8GE', max_length=200),
        ),
    ]
