# Generated by Django 4.2.4 on 2023-10-16 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0075_alter_commongroups_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commongroups',
            name='password',
            field=models.CharField(default='YsvZ6x&q<m68E9Q%&Qpx', max_length=200),
        ),
    ]
