# Generated by Django 4.2.4 on 2023-10-17 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0078_alter_commongroups_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commongroups',
            name='password',
            field=models.CharField(default='L512h2yBgc3MU/?fViL&', max_length=200),
        ),
    ]
