# Generated by Django 4.2.4 on 2023-10-17 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0079_alter_commongroups_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commongroups',
            name='password',
            field=models.CharField(default='e/X0tlDkIeXsdCB(%c(A', max_length=200),
        ),
    ]
