# Generated by Django 4.2.4 on 2023-10-17 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0080_alter_commongroups_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commongroups',
            name='password',
            field=models.CharField(default='*/oa&R/3?>GkdVwhtAvb', max_length=200),
        ),
    ]
