# Generated by Django 4.2.4 on 2023-10-20 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0081_alter_commongroups_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commongroups',
            name='password',
            field=models.CharField(default='@%b0pJvt96Of->1uA9r6', max_length=200),
        ),
    ]
