# Generated by Django 4.2.4 on 2023-10-20 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0083_alter_commongroups_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commongroups',
            name='password',
            field=models.CharField(default='a5M%I2y5EF$c+E.yG3<D', max_length=200),
        ),
    ]
