# Generated by Django 4.2.4 on 2023-10-20 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0084_alter_commongroups_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commongroups',
            name='password',
            field=models.CharField(default='B8sCf$K0g=(.RW++F2xi', max_length=200),
        ),
    ]
