# Generated by Django 4.2.4 on 2023-10-20 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0085_alter_commongroups_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commongroups',
            name='password',
            field=models.CharField(default='+bCiCKlk5K3>-vwiOJw2', max_length=200),
        ),
    ]
