# Generated by Django 4.2.4 on 2023-10-21 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0086_alter_commongroups_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commongroups',
            name='password',
            field=models.CharField(default='7F=>1rosU3fv+!E-nYI3', max_length=200),
        ),
    ]
