# Generated by Django 4.2.4 on 2023-10-24 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0089_alter_commongroups_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commongroups',
            name='password',
            field=models.CharField(default='w2&$RE-7*G%XA)s1YzLN', max_length=200),
        ),
    ]
