# Generated by Django 4.2.4 on 2023-10-25 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0091_alter_commongroups_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commongroups',
            name='password',
            field=models.CharField(default='$8U?ZZ4u33<5wwVj*GX)', max_length=200),
        ),
    ]
