# Generated by Django 4.2.4 on 2023-10-26 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0092_alter_commongroups_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commongroups',
            name='password',
            field=models.CharField(default='kT7hUt$(ehWiQPM0<iBH', max_length=200),
        ),
    ]
