# Generated by Django 4.2.4 on 2023-10-26 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0093_alter_commongroups_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commongroups',
            name='password',
            field=models.CharField(default='v)7+4bpKiH0Cu$y>s(88', max_length=200),
        ),
    ]
