# Generated by Django 4.2.4 on 2023-11-01 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0095_alter_commongroups_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commongroups',
            name='password',
            field=models.CharField(default='cMp1bH5-qa6gh/0C%pe%', max_length=200),
        ),
    ]
