# Generated by Django 4.2.4 on 2023-11-04 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0100_alter_commongroups_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commongroups',
            name='password',
            field=models.CharField(default='y)7f82ENnj&(fpKVqUv)', max_length=200),
        ),
    ]
