# Generated by Django 4.2.4 on 2023-11-04 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0101_alter_commongroups_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commongroups',
            name='password',
            field=models.CharField(default='J@Gb@)FNJsiTrdcd6!B0', max_length=200),
        ),
    ]
