# Generated by Django 4.2.4 on 2023-11-04 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0102_alter_commongroups_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commongroups',
            name='password',
            field=models.CharField(default='Q$tcA7vHu%4!.tF!+48K', max_length=200),
        ),
    ]
