# Generated by Django 4.2.4 on 2023-11-05 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0105_alter_commongroups_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commongroups',
            name='password',
            field=models.CharField(default='5AaTsv0VRQ!s(hOMnYrO', max_length=200),
        ),
    ]
