# Generated by Django 4.2.4 on 2023-11-05 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0106_alter_commongroups_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commongroups',
            name='password',
            field=models.CharField(default='Wbeg&8ttyk0oZ4CW$ZF!', max_length=200),
        ),
    ]
