# Generated by Django 4.2.4 on 2023-11-06 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0109_alter_commongroups_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commongroups',
            name='password',
            field=models.CharField(default='wK<no..zQDmNklHkVtx!', max_length=200),
        ),
    ]
