# Generated by Django 4.2.4 on 2023-11-06 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0110_alter_commongroups_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='commongroups',
            name='allow_invitations',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='commongroups',
            name='password',
            field=models.CharField(default='!L=&Eh&j31>$a*Vu3kCR', max_length=200),
        ),
    ]
