# Generated by Django 4.2.4 on 2023-11-18 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0111_commongroups_allow_invitations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commongroups',
            name='password',
            field=models.CharField(default='sA8KYHT<cr(s3?KMW4p?', max_length=200),
        ),
    ]
