# Generated by Django 4.2.4 on 2023-11-18 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0112_alter_commongroups_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commongroups',
            name='password',
            field=models.CharField(default='Idqp9/z03VIi9anYgATh', max_length=200),
        ),
    ]
