# Generated by Django 4.2.4 on 2023-11-18 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0113_alter_commongroups_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commongroups',
            name='password',
            field=models.CharField(default='h)Wcsr0iMH5wvTCdIO5v', max_length=200),
        ),
    ]
