# Generated by Django 4.2.4 on 2023-11-18 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0117_alter_commongroups_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commongroups',
            name='password',
            field=models.CharField(default='(a2eQ>R+tI=/S2esr8ia', max_length=200),
        ),
    ]
