# Generated by Django 4.2.4 on 2023-11-18 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0119_alter_commongroups_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commongroups',
            name='password',
            field=models.CharField(default='KBBYYtHSD.t!iu@U9oT2', max_length=200),
        ),
    ]
