# Generated by Django 4.2.4 on 2023-11-18 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0120_alter_commongroups_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commongroups',
            name='password',
            field=models.CharField(default='F!r.o!Y&?sTdwEz=ce1q', max_length=200),
        ),
    ]
