# Generated by Django 4.2.4 on 2023-11-18 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0121_alter_commongroups_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commongroups',
            name='password',
            field=models.CharField(default='x46b-pRx4fj(NO$coVlH', max_length=200),
        ),
    ]
