# Generated by Django 4.2.4 on 2023-11-19 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0123_alter_commongroups_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commongroups',
            name='password',
            field=models.CharField(default=')ZQlAfHg-Evlzlf-8jtw', max_length=200),
        ),
    ]
