# Generated by Django 4.2.4 on 2023-11-19 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0124_alter_commongroups_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commongroups',
            name='password',
            field=models.CharField(default='NIW<QVGbvQogwcK.$=WZ', max_length=200),
        ),
    ]
