# Generated by Django 4.2.4 on 2023-11-19 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0125_alter_commongroups_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commongroups',
            name='password',
            field=models.CharField(default='pUW4eS>)Nj$O&+)4E3ps', max_length=200),
        ),
    ]
