# Generated by Django 4.2.4 on 2023-11-19 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0128_alter_commongroups_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commongroups',
            name='password',
            field=models.CharField(default='@pF$cFCHB@@-TLQQRDKS', max_length=200),
        ),
    ]
