# Generated by Django 4.2.4 on 2023-11-20 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0129_alter_commongroups_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commongroups',
            name='password',
            field=models.CharField(default='!rVM+TZ9xG>=YMyMDhl=', max_length=200),
        ),
    ]
