# Generated by Django 4.2.4 on 2023-11-21 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0130_alter_commongroups_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commongroups',
            name='password',
            field=models.CharField(default='&?670@x9lla8i(IM%MQs', max_length=200),
        ),
    ]
