# Generated by Django 4.2.4 on 2023-11-22 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0133_alter_commongroups_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commongroups',
            name='password',
            field=models.CharField(default='-(NuH9sK1h=40iL&xARe', max_length=200),
        ),
    ]
