# Generated by Django 4.2.4 on 2023-11-22 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0135_commongroups_can_receipts_be_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commongroups',
            name='password',
            field=models.CharField(default='1=Jdh(+h3-W8@@K5C7cC', max_length=200),
        ),
    ]
