# Generated by Django 4.2.4 on 2023-11-23 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0136_alter_commongroups_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commongroups',
            name='password',
            field=models.CharField(default='7%yE+GKU>903UaCI.<-E', max_length=200),
        ),
    ]
