# Generated by Django 4.2.4 on 2023-11-23 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0140_alter_commongroups_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commongroups',
            name='password',
            field=models.CharField(default='D>0NizArMPz?Y!@/$508', max_length=200),
        ),
    ]
