# Generated by Django 4.2.4 on 2023-11-23 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0141_alter_commongroups_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commongroups',
            name='password',
            field=models.CharField(default='MMOj3sHcFFb-Pg!4SlTi', max_length=200),
        ),
    ]
