# Generated by Django 4.2.4 on 2023-11-23 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0143_alter_commongroups_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commongroups',
            name='password',
            field=models.CharField(default='@7qSEx8<m3m&N8O/1&U&', max_length=200),
        ),
    ]
