# Generated by Django 4.2.4 on 2023-12-01 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0144_alter_commongroups_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commongroups',
            name='password',
            field=models.CharField(default='2L)Ju+0aDXeEgD!1VXeG', max_length=200),
        ),
    ]
