# Generated by Django 4.2.4 on 2023-12-01 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0145_alter_commongroups_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commongroups',
            name='password',
            field=models.CharField(default='(X@UK%Eo2S=6&8q)HhW/', max_length=200),
        ),
    ]
