# Generated by Django 4.2.4 on 2023-12-01 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0147_alter_commongroups_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commongroups',
            name='password',
            field=models.CharField(default='pO@.FJV8wRD+..2Ayt.T', max_length=200),
        ),
    ]
