# Generated by Django 4.2.4 on 2023-12-01 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0149_alter_commongroups_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commongroups',
            name='password',
            field=models.CharField(default='&NrE&u3w5ZblW.lsO7NI', max_length=200),
        ),
    ]
