# Generated by Django 4.2.4 on 2023-12-01 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0152_alter_commongroups_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commongroups',
            name='password',
            field=models.CharField(default='$vBE>4ptZyg7U>$cCeqJ', max_length=200),
        ),
    ]
