# Generated by Django 4.2.4 on 2023-12-01 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0153_alter_commongroups_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commongroups',
            name='password',
            field=models.CharField(default='(B*n$8z7Z58B7MtYCqa+', max_length=200),
        ),
    ]
