# Generated by Django 4.2.4 on 2023-12-03 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0154_alter_commongroups_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commongroups',
            name='password',
            field=models.CharField(default='?ky!FDM.)uDyD815V&*?', max_length=200),
        ),
    ]
