# Generated by Django 4.2.4 on 2023-12-04 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0155_alter_commongroups_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commongroups',
            name='password',
            field=models.CharField(default='Bnby>lf4mcGiE96Y/KJM', max_length=200),
        ),
    ]
