# Generated by Django 4.2.4 on 2023-12-04 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0156_alter_commongroups_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commongroups',
            name='password',
            field=models.CharField(default='RbxLBJn/vmk*IRYLxT1)', max_length=200),
        ),
    ]
