# Generated by Django 4.2.4 on 2023-12-14 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0159_alter_commongroups_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commongroups',
            name='slug',
        ),
        migrations.AlterField(
            model_name='commongroups',
            name='password',
            field=models.CharField(default='xTp&bMw1Q2e<X2s$V2XJ', max_length=200),
        ),
    ]
