# Generated by Django 4.2.4 on 2023-12-28 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0160_remove_commongroups_slug_alter_commongroups_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commongroups',
            name='password',
            field=models.CharField(default='EQL<Jt2%LsRiRaYdz2b?', max_length=200),
        ),
    ]
