# Generated by Django 4.2.4 on 2023-12-29 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0161_alter_commongroups_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commongroups',
            name='password',
            field=models.CharField(default='XP*h6r0U/6KB3HX9n&+0', max_length=200),
        ),
    ]
