# Generated by Django 4.2.4 on 2024-01-04 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0162_alter_commongroups_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commongroups',
            name='password',
            field=models.CharField(default='BJwg9fCvhzH/5)vN+LXG', max_length=200),
        ),
    ]
