# Generated by Django 4.2.4 on 2024-01-06 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0163_alter_commongroups_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commongroups',
            name='password',
            field=models.CharField(default='CS4*)-t/ea4KVHE8Ln!J', max_length=200),
        ),
    ]
