# Generated by Django 4.2.4 on 2024-01-07 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0164_alter_commongroups_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commongroups',
            name='password',
            field=models.CharField(default='H/sdb7I2(.UL>ut2t?pD', max_length=200),
        ),
    ]
