# Generated by Django 4.2.4 on 2024-01-07 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0165_alter_commongroups_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commongroups',
            name='password',
            field=models.CharField(default='9-ob(Y@TW>vQ6Z-EB?$g', max_length=200),
        ),
    ]
