# Generated by Django 4.2.4 on 2024-01-07 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0166_alter_commongroups_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commongroups',
            name='password',
            field=models.CharField(default='HqVF>vv$TKwYeNcY)NTd', max_length=200),
        ),
    ]
