# Generated by Django 4.2.4 on 2024-01-09 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0167_alter_commongroups_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commongroups',
            name='password',
            field=models.CharField(default='EI((CLnGNEuNDb%.6EkC', max_length=200),
        ),
    ]
