# Generated by Django 4.2.4 on 2023-10-08 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_lists', '0006_alter_product_date_added_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.CharField(blank=True, default='1szt.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='regards',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
    ]
