# Generated by Django 4.2.4 on 2023-10-12 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0009_subcategories_icon_alter_basecategories_color'),
        ('shopping_lists', '0007_product_quantity_product_regards'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.basecategories'),
        ),
    ]
