# Generated by Django 4.2.4 on 2023-10-16 00:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0066_alter_commongroups_password'),
        ('shopping_lists', '0009_remove_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedShoppingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_in_realization', models.BooleanField(default=False)),
                ('base_list', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shopping_lists.shoppinglist')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.commongroups')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('realizators', models.ManyToManyField(related_name='realizators', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
