# Generated by Django 4.2.4 on 2023-10-20 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_lists', '0010_sharedshoppinglist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='ListProduct',
        ),
        migrations.AlterModelOptions(
            name='listproduct',
            options={'verbose_name_plural': 'list products'},
        ),
    ]
