# Generated by Django 4.2.4 on 2023-10-20 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_lists', '0011_rename_product_listproduct_alter_listproduct_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='listproduct',
            name='is_bought',
            field=models.BooleanField(default=False),
        ),
    ]
