# Generated by Django 4.2.4 on 2023-10-25 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_lists', '0012_listproduct_is_bought'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='is_shared',
            field=models.BooleanField(default=False),
        ),
    ]
