# Generated by Django 4.2.4 on 2023-11-01 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_lists', '0015_shoppinglist_group_shoppinglist_realizators_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listproduct',
            name='selected_list',
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='products',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shopping_lists.listproduct'),
        ),
    ]
