# Generated by Django 4.2.4 on 2023-11-03 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_lists', '0017_remove_shoppinglist_products_shoppinglist_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglist',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, to='shopping_lists.listproduct'),
        ),
    ]
