# Generated by Django 4.2.4 on 2023-11-03 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0099_alter_commongroups_password'),
        ('shopping_lists', '0018_alter_shoppinglist_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppinglist',
            name='products',
        ),
        migrations.AddField(
            model_name='listproduct',
            name='shopping_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shopping_lists.shoppinglist'),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='groups.commongroups'),
        ),
    ]
