# Generated by Django 4.2.4 on 2024-01-04 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_lists', '0020_shoppinglist_display_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='logs',
            field=models.TextField(blank=True, null=True),
        ),
    ]
