# Generated by Django 4.2.4 on 2024-01-06 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_lists', '0021_shoppinglist_logs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglist',
            name='logs',
            field=models.TextField(default=''),
        ),
    ]
