# Generated by Django 4.2.4 on 2024-01-07 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_lists', '0022_alter_shoppinglist_logs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglist',
            name='regards',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
